name: SneakyPocketbase
version: "1.0"
main: com.danidipp.sneakypocketbase.SneakyPocketbase
api-version: "1.20"
authors:
  - DaniDipp
description: "Paper Plugin for interacting with Pocketbase"
dependencies:
    server:
        MagicSpells:
            load: BEFORE
            required: false